### PR TITLE
Add additional resources from github docs

### PR DESCRIPTION
**Pull request by rossturk**
Signed-off-by: Ross Turk <ross@rossturk.com>

This adds five new documents to the website that currently live at https://marquezproject.github.io/marquez/ into the top of the Resources section:
- Migrating marquez database manually via flyway
- Deployment Overview
- Running on AWS
- Run State Transitions
- Lifecycle Overview

It also adds the OpenAPI spec into `/static` so that it will be available in the root of marquezproject.ai, and links to it from Resources. It will be important to publish a new `openapi.html` **here** instead of in `marquezproject/marquez` when it changes.

(merges to main here should automatically ship a new site!)

Closes: https://github.com/MarquezProject/marquez/issues/2090

### CODE REVIEW

**Comment by howardyoo** [comment]
One thing that I noticed, while reviewing was the openapi.html seeemed to be of the older version.
image
was what I saw when ran it locally vial gatsby, and
image
is the most recent version of openapi.html.

Hope the openapi.html would be updated with the latest and the greatest before getting merged.

**Comment by howardyoo** [comment]
Since we are going to be deprecating https://marquezproject.github.io/marquez/ , perhaps, this PR should also contain the update on the message on that website letting users know that this website is going to go away, and post a link to the https://marquezproject.ai/ , so that user would know what's going on, and also be able to find the new website easily.

**Review by howardyoo — COMMENTED** [review]
1. openapi.html seems to be of an older version. Would be great to update the openapi.html file with the most recent version available.
2. Would be great for the old https://marquezproject.github.io/marquez/ website's index page to contain notice at the top notifying users of the deprecation, and also have a link to the new website https://marquezproject.ai/ on that page, so that users would how to access the new website.

**Comment by rossturk** [comment]
> * openapi.html seems to be of an older version. Would be great to update the openapi.html file with the most recent version available.

Oops! I grabbed it from the Marquez repo, but clearly I forgot to `git pull` first 😦 I updated it now.

> * Would be great for the old https://marquezproject.github.io/marquez/ website's index page to contain notice at the top notifying users of the deprecation, and also have a link to the new website https://marquezproject.ai/ on that page, so that users would how to access the new website.

I agree - I was actually going to do a redirect from the old website to the new one once all of the content was migrated over. Expect that in a subsequent pull request 👍 I wanted to make sure everyone was comfortable with the migration first.

**Review by howardyoo — APPROVED** [review]
Reviewed, LGTM!

**Pull request merged**
